-- ACTIVITY 8

select * from orders;


SELECT CUSTOMER_ID, MAX(PURCHASE_AMOUNT) FROM orders GROUP BY  CUSTOMER_ID;

SELECT SALESMAN_ID,MAX(PURCHASE_AMOUNT) FROM orders  WHERE ORDER_DATE = '17-AUG-12' GROUP BY SALESMAN_ID;


SELECT CUSTOMER_ID, MAX(PURCHASE_AMOUNT), ORDER_DATE FROM orders GROUP BY CUSTOMER_ID, ORDER_DATE HAVING MAX(PURCHASE_AMOUNT) IN (2030, 3450, 5760, 6000);